-- Tách riêng dữ liệu nền để khi cần có thể chạy lại cho nhanh.
SET search_path TO public;
SET client_encoding = 'UTF8';
BEGIN;

-- 1. Role mẫu
INSERT INTO ROLE (RoleID, RoleName, Permissions, Description) VALUES ('7f271acf-fbf9-599d-a8f7-260df6b806ce', 'admin', ARRAY['stock.view','stock.adjust','purchase_order.create','purchase_order.approve','transfer.create','transfer.approve','order.create','order.cancel','report.export','channel.manage','user.manage']::TEXT[], 'Quản trị viên toàn hệ thống') ON CONFLICT (RoleID) DO UPDATE SET RoleName = EXCLUDED.RoleName, Permissions = EXCLUDED.Permissions, Description = EXCLUDED.Description;
INSERT INTO ROLE (RoleID, RoleName, Permissions, Description) VALUES ('c8c586d3-6628-5720-b67a-9990b7c3cd82', 'warehouse_staff', ARRAY['stock.view','purchase_order.create','transfer.create']::TEXT[], 'Nhân viên kho') ON CONFLICT (RoleID) DO UPDATE SET RoleName = EXCLUDED.RoleName, Permissions = EXCLUDED.Permissions, Description = EXCLUDED.Description;
INSERT INTO ROLE (RoleID, RoleName, Permissions, Description) VALUES ('68acc8bf-605c-5b59-aa08-d49fc986bbce', 'sales_staff', ARRAY['stock.view','order.create']::TEXT[], 'Nhân viên bán hàng') ON CONFLICT (RoleID) DO UPDATE SET RoleName = EXCLUDED.RoleName, Permissions = EXCLUDED.Permissions, Description = EXCLUDED.Description;
INSERT INTO ROLE (RoleID, RoleName, Permissions, Description) VALUES ('de3956f2-e623-586b-8da4-d25533690753', 'branch_manager', ARRAY['stock.view','stock.adjust','purchase_order.approve','transfer.approve','order.create','report.export']::TEXT[], 'Quản lý chi nhánh') ON CONFLICT (RoleID) DO UPDATE SET RoleName = EXCLUDED.RoleName, Permissions = EXCLUDED.Permissions, Description = EXCLUDED.Description;

-- 2. Chi nhánh/kho: nguồn hàng đi từ kho trung tâm ra các chi nhánh
INSERT INTO BRANCH (BranchID, BranchName, BranchType, Address, Province, PhoneNumber, Email, OpenTime, CloseTime, Status) VALUES ('50b58fa0-2b4d-5aa2-9936-2242c9ad6c3a', 'Kho trung tâm SilkRoad HCM', 'central_warehouse', 'Khu công nghiệp Tân Bình, TP. Hồ Chí Minh', 'TP. Hồ Chí Minh', '02870010001', 'central@silkroad.local', '08:00', '22:00', 'active') ON CONFLICT (BranchID) DO UPDATE SET BranchName=EXCLUDED.BranchName, BranchType=EXCLUDED.BranchType, Address=EXCLUDED.Address, Province=EXCLUDED.Province, PhoneNumber=EXCLUDED.PhoneNumber, Email=EXCLUDED.Email, Status=EXCLUDED.Status;
INSERT INTO BRANCH (BranchID, BranchName, BranchType, Address, Province, PhoneNumber, Email, OpenTime, CloseTime, Status) VALUES ('db49bb67-bd1d-5fd9-881e-abe4950bec95', 'Chi nhánh Quận 1', 'retail_store', '12 Nguyễn Huệ, Quận 1', 'TP. Hồ Chí Minh', '02870010002', 'q1@silkroad.local', '08:00', '22:00', 'active') ON CONFLICT (BranchID) DO UPDATE SET BranchName=EXCLUDED.BranchName, BranchType=EXCLUDED.BranchType, Address=EXCLUDED.Address, Province=EXCLUDED.Province, PhoneNumber=EXCLUDED.PhoneNumber, Email=EXCLUDED.Email, Status=EXCLUDED.Status;
INSERT INTO BRANCH (BranchID, BranchName, BranchType, Address, Province, PhoneNumber, Email, OpenTime, CloseTime, Status) VALUES ('e830b63a-35d2-5142-99ce-fec1c4e9d6e5', 'Chi nhánh Quận 7', 'retail_store', '68 Nguyễn Thị Thập, Quận 7', 'TP. Hồ Chí Minh', '02870010003', 'q7@silkroad.local', '08:00', '22:00', 'active') ON CONFLICT (BranchID) DO UPDATE SET BranchName=EXCLUDED.BranchName, BranchType=EXCLUDED.BranchType, Address=EXCLUDED.Address, Province=EXCLUDED.Province, PhoneNumber=EXCLUDED.PhoneNumber, Email=EXCLUDED.Email, Status=EXCLUDED.Status;
INSERT INTO BRANCH (BranchID, BranchName, BranchType, Address, Province, PhoneNumber, Email, OpenTime, CloseTime, Status) VALUES ('8eb84949-d985-59ba-9d15-6c0dfc18fe00', 'Chi nhánh Hà Nội', 'retail_store', '88 Cầu Giấy, Hà Nội', 'Hà Nội', '02470010004', 'hanoi@silkroad.local', '08:00', '22:00', 'active') ON CONFLICT (BranchID) DO UPDATE SET BranchName=EXCLUDED.BranchName, BranchType=EXCLUDED.BranchType, Address=EXCLUDED.Address, Province=EXCLUDED.Province, PhoneNumber=EXCLUDED.PhoneNumber, Email=EXCLUDED.Email, Status=EXCLUDED.Status;
INSERT INTO BRANCH (BranchID, BranchName, BranchType, Address, Province, PhoneNumber, Email, OpenTime, CloseTime, Status) VALUES ('8d0f230d-66e9-5f27-a730-1510d127cf12', 'Chi nhánh Đà Nẵng', 'retail_store', '25 Bạch Đằng, Đà Nẵng', 'Đà Nẵng', '02367001005', 'danang@silkroad.local', '08:00', '22:00', 'active') ON CONFLICT (BranchID) DO UPDATE SET BranchName=EXCLUDED.BranchName, BranchType=EXCLUDED.BranchType, Address=EXCLUDED.Address, Province=EXCLUDED.Province, PhoneNumber=EXCLUDED.PhoneNumber, Email=EXCLUDED.Email, Status=EXCLUDED.Status;
INSERT INTO BRANCH (BranchID, BranchName, BranchType, Address, Province, PhoneNumber, Email, OpenTime, CloseTime, Status) VALUES ('f06457a4-0235-5f14-99c5-6a99ca00c407', 'Chi nhánh Cần Thơ', 'retail_store', '40 Hòa Bình, Cần Thơ', 'Cần Thơ', '02927001006', 'cantho@silkroad.local', '08:00', '22:00', 'active') ON CONFLICT (BranchID) DO UPDATE SET BranchName=EXCLUDED.BranchName, BranchType=EXCLUDED.BranchType, Address=EXCLUDED.Address, Province=EXCLUDED.Province, PhoneNumber=EXCLUDED.PhoneNumber, Email=EXCLUDED.Email, Status=EXCLUDED.Status;

-- 3. User nghiệp vụ mẫu
INSERT INTO USERS (UserID, FullName, Username, PhoneNumber, Email, RoleID, BranchID, Status) VALUES ('896960f9-02a2-5310-9fcd-7cd68076d8ce', 'Admin - Quản trị hệ thống', 'admin', NULL, 'admin@silkroad.local', '7f271acf-fbf9-599d-a8f7-260df6b806ce', '50b58fa0-2b4d-5aa2-9936-2242c9ad6c3a', 'active') ON CONFLICT (UserID) DO UPDATE SET FullName=EXCLUDED.FullName, Username=EXCLUDED.Username, Email=EXCLUDED.Email, RoleID=EXCLUDED.RoleID, BranchID=EXCLUDED.BranchID, Status=EXCLUDED.Status;
INSERT INTO USERS (UserID, FullName, Username, PhoneNumber, Email, RoleID, BranchID, Status) VALUES ('1c4c7eb4-ce3b-5be5-b012-2da6919858ce', 'Kho Trung Tâm', 'warehouse', NULL, 'warehouse@silkroad.local', 'c8c586d3-6628-5720-b67a-9990b7c3cd82', '50b58fa0-2b4d-5aa2-9936-2242c9ad6c3a', 'active') ON CONFLICT (UserID) DO UPDATE SET FullName=EXCLUDED.FullName, Username=EXCLUDED.Username, Email=EXCLUDED.Email, RoleID=EXCLUDED.RoleID, BranchID=EXCLUDED.BranchID, Status=EXCLUDED.Status;
INSERT INTO USERS (UserID, FullName, Username, PhoneNumber, Email, RoleID, BranchID, Status) VALUES ('7c9a3b7e-c6f1-5b4c-b802-46c914431c11', 'NV Bán hàng Q1', 'sales_q1', NULL, 'sales.q1@silkroad.local', '68acc8bf-605c-5b59-aa08-d49fc986bbce', 'db49bb67-bd1d-5fd9-881e-abe4950bec95', 'active') ON CONFLICT (UserID) DO UPDATE SET FullName=EXCLUDED.FullName, Username=EXCLUDED.Username, Email=EXCLUDED.Email, RoleID=EXCLUDED.RoleID, BranchID=EXCLUDED.BranchID, Status=EXCLUDED.Status;
INSERT INTO USERS (UserID, FullName, Username, PhoneNumber, Email, RoleID, BranchID, Status) VALUES ('4b285660-7f65-53ed-a3b7-583849b63280', 'Quản lý Hà Nội', 'manager_hn', NULL, 'manager.hn@silkroad.local', 'de3956f2-e623-586b-8da4-d25533690753', '8eb84949-d985-59ba-9d15-6c0dfc18fe00', 'active') ON CONFLICT (UserID) DO UPDATE SET FullName=EXCLUDED.FullName, Username=EXCLUDED.Username, Email=EXCLUDED.Email, RoleID=EXCLUDED.RoleID, BranchID=EXCLUDED.BranchID, Status=EXCLUDED.Status;

-- 4. Danh mục sản phẩm
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('40bb96e8-c182-5917-8723-7e762570b460', NULL, 'Thời trang nam', 'thoi-trang-nam', 1, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('daeae8d2-7ce6-5251-9192-23d8dbed4718', NULL, 'Thời trang nữ', 'thoi-trang-nu', 2, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('420321f9-c478-5541-a4da-a9a4f15bdfa8', NULL, 'Trẻ em', 'tre-em', 3, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('d845b191-beae-52fb-903c-be5c9da87b06', NULL, 'Phụ kiện', 'phu-kien', 4, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('12610742-5dda-5b34-8676-397c69c1b91a', '40bb96e8-c182-5917-8723-7e762570b460', 'Áo thun nam', 'ao-thun-nam', 11, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('b4612092-60ab-57e1-8ac2-14193afa1b36', '40bb96e8-c182-5917-8723-7e762570b460', 'Áo sơ mi nam', 'ao-so-mi-nam', 12, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('8f4a212d-4bba-52ef-aa75-7f39527dd604', '40bb96e8-c182-5917-8723-7e762570b460', 'Áo khoác nam', 'ao-khoac-nam', 13, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('0a9c895c-3c37-5f55-9045-413c1551aff3', '40bb96e8-c182-5917-8723-7e762570b460', 'Quần nam', 'quan-nam', 14, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('6dabca00-cd0b-5b55-8cc9-46407bab3f2d', 'daeae8d2-7ce6-5251-9192-23d8dbed4718', 'Áo thun nữ', 'ao-thun-nu', 21, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('327a7c1b-42ad-5a80-8fd2-a7772e8fe78c', 'daeae8d2-7ce6-5251-9192-23d8dbed4718', 'Áo sơ mi nữ', 'ao-so-mi-nu', 22, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('06af9b97-d9ad-50dd-9f36-60f7511bd92b', 'daeae8d2-7ce6-5251-9192-23d8dbed4718', 'Áo dệt kim nữ', 'ao-det-kim-nu', 23, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('679c81ea-f492-5af4-a293-a6a952475da1', 'daeae8d2-7ce6-5251-9192-23d8dbed4718', 'Áo khoác nữ', 'ao-khoac-nu', 24, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('c2719b82-8bfa-57df-9c09-6941153c68bf', 'daeae8d2-7ce6-5251-9192-23d8dbed4718', 'Đầm và váy nữ', 'dam-vay-nu', 25, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('aa1b5991-a49b-5dc9-a25c-98d1a2b7f985', 'daeae8d2-7ce6-5251-9192-23d8dbed4718', 'Đồ thể thao', 'do-the-thao', 26, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('1a44e21e-ba68-5e92-84d0-1d13ebcee864', '420321f9-c478-5541-a4da-a9a4f15bdfa8', 'Đồ trẻ em', 'do-tre-em', 31, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();
INSERT INTO PRODUCT_CATEGORY (CategoryID, ParentCategoryID, CategoryName, Slug, DisplayOrder, Status) VALUES ('33e5377e-2c3e-5cb5-bb16-c56493a8fb9a', 'd845b191-beae-52fb-903c-be5c9da87b06', 'Đồ lót và phụ kiện', 'do-lot-phu-kien', 41, 'active') ON CONFLICT (CategoryID) DO UPDATE SET ParentCategoryID=EXCLUDED.ParentCategoryID, CategoryName=EXCLUDED.CategoryName, Slug=EXCLUDED.Slug, DisplayOrder=EXCLUDED.DisplayOrder, Status=EXCLUDED.Status, UpdatedAt=NOW();

-- 5. Thuộc tính size và màu
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('7c13b9f5-959e-522e-8689-c8104673cf34', 'size', 'S', 'S', NULL, 1, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('4801de60-aed7-543b-9e3a-88f5be8fbedf', 'size', 'M', 'M', NULL, 2, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('a635a2b4-ceca-54b1-9bc7-9a66cd385800', 'size', 'L', 'L', NULL, 3, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('3c9f6bc2-aa89-50bc-8df3-6b55e3a39d66', 'size', 'XL', 'XL', NULL, 4, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('631bf523-8af4-5c7c-8bc4-13c69a1feecf', 'size', '29', '29', NULL, 5, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('6bf7e701-0a1c-56de-ab8b-3bcba25d755a', 'size', '30', '30', NULL, 6, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('e7c5341e-5ba0-591e-9524-ad7de5b7b278', 'size', '31', '31', NULL, 7, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('b1766451-1d94-50fa-9885-f84047c95cf0', 'size', '32', '32', NULL, 8, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('d8549fdf-fba8-54da-b213-461b98c45f41', 'size', '100', '100', NULL, 9, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('d88fd20c-b4c3-52be-bd91-47cefb04f58a', 'size', '110', '110', NULL, 10, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('0b44ed62-0696-5064-abf8-6130004873e6', 'size', '120', '120', NULL, 11, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('9565592e-6027-568a-902c-b842687905ea', 'size', '130', '130', NULL, 12, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('5a5bb3ab-b0b3-5e0d-bf69-6eda78933229', 'size', 'ONE SIZE', 'ONE SIZE', NULL, 13, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('53cd93b1-e2e1-5116-bd94-ad06879680ac', 'color', 'BLACK', 'Đen', '#111111', 1, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('3b1b2194-9ffa-5b0d-b0a1-b6117c6638e4', 'color', 'WHITE', 'Trắng', '#FFFFFF', 2, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('e1c2642e-8d0a-5066-9ab8-c75369608363', 'color', 'BEIGE', 'Be', '#D6C2A1', 3, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('4b8e3c72-d357-5621-aae3-a45bca08fa78', 'color', 'NAVY', 'Xanh navy', '#16233F', 4, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('c13c4415-615c-5fe4-9681-006b99166d03', 'color', 'RED', 'Đỏ', '#B83B3B', 5, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('d4d421d0-ac72-58c3-a91b-db4ffd79dfed', 'color', 'GRAY', 'Xám', '#858585', 6, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('21f0b14c-672e-58c8-8923-7dc8fe0dbefe', 'color', 'GREEN', 'Xanh lá', '#2F6B4F', 7, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('2397b9a7-5994-54a8-83a6-7a2730c76be1', 'color', 'BLUE', 'Xanh dương', '#2D5F9A', 8, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('cc3b4b58-967c-5bb3-b6fe-4db7bc8a1dea', 'color', 'PINK', 'Hồng', '#E9A9B7', 9, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('c9964068-581e-5b66-9a2d-e6ee928bd179', 'color', 'CREAM', 'Kem', '#F1E5C8', 10, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('546763a1-6163-53ed-a63f-54c8fef4756b', 'color', 'BROWN', 'Nâu', '#7A4E2B', 11, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;
INSERT INTO ATTRIBUTE (AttributeID, AttributeType, Value, DisplayValue, HexCode, SortOrder, Status) VALUES ('6957354c-fe1e-5bf8-b2e5-605586083ed3', 'color', 'OLIVE', 'Olive', '#667046', 12, 'active') ON CONFLICT (AttributeType, Value) DO UPDATE SET DisplayValue=EXCLUDED.DisplayValue, HexCode=EXCLUDED.HexCode, SortOrder=EXCLUDED.SortOrder, Status=EXCLUDED.Status;

-- 6. Kênh bán
INSERT INTO SALES_CHANNEL (ChannelID, ChannelName, ChannelType, Status, ChannelConfig) VALUES ('0d15aaaa-15d5-51cd-85dc-31927954274b', 'POS', 'pos', 'active', '{"seed_batch":"web_real_literal_300_v3","auto_sync_stock":true,"source":"sample_data"}'::JSONB) ON CONFLICT (ChannelID) DO UPDATE SET ChannelName=EXCLUDED.ChannelName, ChannelType=EXCLUDED.ChannelType, Status=EXCLUDED.Status, ChannelConfig=EXCLUDED.ChannelConfig;
INSERT INTO SALES_CHANNEL (ChannelID, ChannelName, ChannelType, Status, ChannelConfig) VALUES ('b634ca62-8232-5d32-bc12-a4a040cab138', 'Website', 'website', 'active', '{"seed_batch":"web_real_literal_300_v3","auto_sync_stock":true,"source":"sample_data"}'::JSONB) ON CONFLICT (ChannelID) DO UPDATE SET ChannelName=EXCLUDED.ChannelName, ChannelType=EXCLUDED.ChannelType, Status=EXCLUDED.Status, ChannelConfig=EXCLUDED.ChannelConfig;
INSERT INTO SALES_CHANNEL (ChannelID, ChannelName, ChannelType, Status, ChannelConfig) VALUES ('fa48c4f5-ad1b-5d58-a317-e30394065809', 'Shopee', 'shopee', 'active', '{"seed_batch":"web_real_literal_300_v3","auto_sync_stock":true,"source":"sample_data"}'::JSONB) ON CONFLICT (ChannelID) DO UPDATE SET ChannelName=EXCLUDED.ChannelName, ChannelType=EXCLUDED.ChannelType, Status=EXCLUDED.Status, ChannelConfig=EXCLUDED.ChannelConfig;
INSERT INTO SALES_CHANNEL (ChannelID, ChannelName, ChannelType, Status, ChannelConfig) VALUES ('0b0001b6-ed88-5e31-8f30-00c6395aecad', 'TikTok Shop', 'tiktok', 'active', '{"seed_batch":"web_real_literal_300_v3","auto_sync_stock":true,"source":"sample_data"}'::JSONB) ON CONFLICT (ChannelID) DO UPDATE SET ChannelName=EXCLUDED.ChannelName, ChannelType=EXCLUDED.ChannelType, Status=EXCLUDED.Status, ChannelConfig=EXCLUDED.ChannelConfig;
INSERT INTO SALES_CHANNEL (ChannelID, ChannelName, ChannelType, Status, ChannelConfig) VALUES ('f9ebd2bf-773e-52b0-ac00-a295f60a183d', 'Facebook Shop', 'facebook', 'active', '{"seed_batch":"web_real_literal_300_v3","auto_sync_stock":true,"source":"sample_data"}'::JSONB) ON CONFLICT (ChannelID) DO UPDATE SET ChannelName=EXCLUDED.ChannelName, ChannelType=EXCLUDED.ChannelType, Status=EXCLUDED.Status, ChannelConfig=EXCLUDED.ChannelConfig;
INSERT INTO SALES_CHANNEL (ChannelID, ChannelName, ChannelType, Status, ChannelConfig) VALUES ('3eb118d9-5a7d-560f-9f5d-8b97bd331141', 'Lazada', 'lazada', 'active', '{"seed_batch":"web_real_literal_300_v3","auto_sync_stock":true,"source":"sample_data"}'::JSONB) ON CONFLICT (ChannelID) DO UPDATE SET ChannelName=EXCLUDED.ChannelName, ChannelType=EXCLUDED.ChannelType, Status=EXCLUDED.Status, ChannelConfig=EXCLUDED.ChannelConfig;

-- 7. Nhà cung cấp
INSERT INTO SUPPLIER (SupplierID, SupplierName, TaxCode, PhoneNumber, Email, Address, PaymentTermDays, Status) VALUES ('e3231c3c-05b9-54a5-8491-7ac1f365271b', 'Routine Việt Nam', '0315299911', '0900000000', 'ncc-routine@silkroad.local', 'Nhà cung cấp tham khảo cho seed SilkRoad', 15, 'active') ON CONFLICT (SupplierID) DO UPDATE SET SupplierName=EXCLUDED.SupplierName, TaxCode=EXCLUDED.TaxCode, Email=EXCLUDED.Email, PaymentTermDays=EXCLUDED.PaymentTermDays, Status=EXCLUDED.Status;
INSERT INTO SUPPLIER (SupplierID, SupplierName, TaxCode, PhoneNumber, Email, Address, PaymentTermDays, Status) VALUES ('b7dea009-62e9-545d-af6c-b1e189e7ff4d', 'UNIQLO Việt Nam', '0315333904', '0900000000', 'ncc-uniqlo@silkroad.local', 'Nhà cung cấp tham khảo cho seed SilkRoad', 15, 'active') ON CONFLICT (SupplierID) DO UPDATE SET SupplierName=EXCLUDED.SupplierName, TaxCode=EXCLUDED.TaxCode, Email=EXCLUDED.Email, PaymentTermDays=EXCLUDED.PaymentTermDays, Status=EXCLUDED.Status;
INSERT INTO SUPPLIER (SupplierID, SupplierName, TaxCode, PhoneNumber, Email, Address, PaymentTermDays, Status) VALUES ('36c585c7-370c-5965-962e-d8a7e88b3bc9', 'H&M Việt Nam', '0314500890', '0900000000', 'ncc-hm@silkroad.local', 'Nhà cung cấp tham khảo cho seed SilkRoad', 15, 'active') ON CONFLICT (SupplierID) DO UPDATE SET SupplierName=EXCLUDED.SupplierName, TaxCode=EXCLUDED.TaxCode, Email=EXCLUDED.Email, PaymentTermDays=EXCLUDED.PaymentTermDays, Status=EXCLUDED.Status;
INSERT INTO SUPPLIER (SupplierID, SupplierName, TaxCode, PhoneNumber, Email, Address, PaymentTermDays, Status) VALUES ('1b599a7b-f8ec-597b-856c-17c532591684', 'ZARA Việt Nam', '0312404551', '0900000000', 'ncc-zara@silkroad.local', 'Nhà cung cấp tham khảo cho seed SilkRoad', 15, 'active') ON CONFLICT (SupplierID) DO UPDATE SET SupplierName=EXCLUDED.SupplierName, TaxCode=EXCLUDED.TaxCode, Email=EXCLUDED.Email, PaymentTermDays=EXCLUDED.PaymentTermDays, Status=EXCLUDED.Status;

COMMIT;

-- Nhà cung cấp mẫu phục vụ quy trình nhập hàng.
-- Điều kiện NOT EXISTS giúp script an toàn khi chạy lại trên local hoặc Supabase web.
INSERT INTO public.supplier (
    supplierid,
    suppliername,
    taxcode,
    phonenumber,
    email,
    address,
    paymenttermdays,
    status
)
SELECT
    v.supplierid,
    v.suppliername,
    v.taxcode,
    v.phonenumber,
    v.email,
    v.address,
    v.paymenttermdays,
    v.status
FROM (
    VALUES
        (gen_random_uuid(), 'Công ty TNHH Dệt May An Phú', '0312456789', '0909123456', 'contact@anphutextile.vn', '12 Nguyễn Văn Linh, Quận 7, TP.HCM', 30, 'active'::record_status),
        (gen_random_uuid(), 'Xưởng May Lụa Đông Á', '0319876543', '0918222333', 'sales@dongasilk.vn', '45 Lê Văn Việt, TP. Thủ Đức, TP.HCM', 15, 'active'::record_status),
        (gen_random_uuid(), 'Nhà cung cấp Vải Cotton Việt', '0104567891', '0987654321', 'cottonviet@supplier.vn', '88 Phố Huế, Hai Bà Trưng, Hà Nội', 30, 'active'::record_status),
        (gen_random_uuid(), 'Công ty Phụ Kiện Thời Trang Minh Khang', '0311122334', '0933444555', 'minhkhang.accessories@gmail.com', '21 Cách Mạng Tháng 8, Quận 3, TP.HCM', 20, 'active'::record_status),
        (gen_random_uuid(), 'Xưởng Gia Công Premium Wear', '3709988776', '0977111222', 'order@premiumwear.vn', 'KCN Sóng Thần, Dĩ An, Bình Dương', 45, 'active'::record_status),
        (gen_random_uuid(), 'Công ty TNHH Vải Linen Mộc', '0102233445', '0966555444', 'linenmoc@fabric.vn', '16 Trần Duy Hưng, Cầu Giấy, Hà Nội', 30, 'active'::record_status),
        (gen_random_uuid(), 'Nhà cung cấp Denim Saigon', '0316677889', '0944888999', 'denimsaigon@supplier.vn', '102 Âu Cơ, Tân Bình, TP.HCM', 25, 'active'::record_status),
        (gen_random_uuid(), 'Công ty Bao Bì Nhãn Mác Hoàng Gia', '0315566778', '0922333444', 'label@hoanggia.vn', '5 Nguyễn Oanh, Gò Vấp, TP.HCM', 15, 'active'::record_status)
) AS v(
    supplierid,
    suppliername,
    taxcode,
    phonenumber,
    email,
    address,
    paymenttermdays,
    status
)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.supplier AS s
    WHERE lower(trim(s.suppliername)) = lower(trim(v.suppliername))
);
